stages:
  - build
  - deploy

build frontend:
  stage: build
  tags:
    - Builder
  script:
    - echo 'Start Build Frontend'
    - cd sa-frontend/
    - npm install
    - npm run build
  artifacts:
    paths:
      - sa-frontend/build/

build maven-webapp:
  stage: build
  tags:
    - Builder
  script:
    - echo 'Build maven app'
    - cd sa-webapp/
    - mvn install
  artifacts:
    paths:
      - sa-webapp/target

build logic:
  stage: build
  tags:
    - Builder
  script:
    - echo 'Build backend'
    - cd sa-logic/sa
    - python3 -m pip install -r requirements.txt
    - python3 -m textblob.download_corpora
    - python3 sentiment_analysis.py
