stages:
  - build frontend
  - build logic
  - build webapp
  - deploy


build sa-frontend:
  stage: build frontend
  tags:
    - Builder
  script:
    - echo 'Start Build Frontend'
    - cd sa-frontend/
    - npm install
    - npm run build
  artifacts:
    paths:
      - build/