stages:
  - remove-all-containers
  - build-run-frontend
  - build-run-webapp
  - build-run-logic

stop_all_containers:
  stage: remove-all-containers
  tags:
    - Builder
  when: manual
  script:
    - docker stop $(docker ps -a -q)
    - docker rm $(docker ps -a -q)
    - docker rmi $(docker images -a -q)

build frontend:
  stage: build-run-frontend
  tags:
    - Builder
  script:
    - echo 'Start Build Frontend'
    - cd sa-frontend/
    - npm install
    - npm run build
    - echo $CI_REGISTRY_PASSWORD | docker login -u $DOCKER_USER_ID --password-stdin
    - docker build -f Dockerfile -t $DOCKER_USER_ID/sentiment-analysis-frontend .
    - docker push $DOCKER_USER_ID/sentiment-analysis-frontend
  artifacts:
    paths:
      - sa-frontend/build/

run frontend:
  stage: build-run-frontend
  tags:
    - Builder
  script:
    - docker run -d -p 80:80 $DOCKER_USER_ID/sentiment-analysis-frontend


build maven-webapp:
  stage: build-run-webapp
  tags:
    - Builder
  script:
    - echo 'Build maven app'
    - cd sa-webapp/
    - mvn install
    - echo $CI_REGISTRY_PASSWORD | docker login -u $DOCKER_USER_ID --password-stdin
    - docker build -f Dockerfile -t $DOCKER_USER_ID/sentiment-analysis-web-app .
    - docker push $DOCKER_USER_ID/sentiment-analysis-web-app
  artifacts:
    paths:
      - sa-webapp/target

run maven-webapp:
  stage: build-run-webapp
  tags:
    - Builder
  script:
    - docker run -d -p 8080:8080 showtime58/sentiment-analysis-web-app


build logic-python:
  stage: build-run-logic
  tags:
    - Builder
  script:
    - echo 'Build backend'
    - cd sa-logic/sa
    - pip3 install -r requirements.txt
    - python3 -m textblob.download_corpora
    - cd ..
    - echo $CI_REGISTRY_PASSWORD | docker login -u $DOCKER_USER_ID --password-stdin
    - docker build -f Dockerfile -t $DOCKER_USER_ID/sentiment-analysis-logic .
    - docker push $DOCKER_USER_ID/sentiment-analysis-logic

run logic-python:
  stage: build-run-logic
  tags:
    - Builder
  script:
    - docker run -d -p 5000:5000 showtime58/sentiment-analysis-web-logic